### ISSUE TITLE
Diagnostic code shown in Problems view is unpleasant

### ISSUE THREAD

**Issue by egamma** [microsoft/typescript-tslint-plugin#16]
Testing: https://github.com/Microsoft/vscode/issues/62092

See the screenshot below and notice:
- each tslint diagnostic has the same diagnostic code 10000
- each diagnostic includes the rule name

At some point it was discussed that error code are strings in the TS language service. If that would be the case then tslint could use the rule name as the diagnostic code

![image](https://user-images.githubusercontent.com/172399/47855217-3b2eb980-dde4-11e8-9956-8e36063d1c5a.png)

Same problem with diagnostic hover

![image](https://user-images.githubusercontent.com/172399/47856947-b2664c80-dde8-11e8-8d00-24534d028db0.png)

**Comment by mjbvz** [comment]
Looks like TS currently only supports using number codes for diagnostics. Will sync with the TS team to see what we can do to improve the experience here

**Comment by egamma** [comment]
@mjbvz some cosmetic tuning would be to use a smaller number than 100000 for the tslint error code.

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint. We are archiving this repo as this project is no longer maintained
