### ISSUE TITLE
Disable rule quick fix does not handle disabling multiple rules properly

### ISSUE THREAD

**Issue by egamma** [microsoft/typescript-tslint-plugin#17]
Testing: https://github.com/Microsoft/vscode/issues/62092

(vscode-tslint has the same limitation)
When a line has multiple rule violations and you want to disable more then one, then the quick fix doesn´t handle this case properly and generates multiple lines
![image](https://user-images.githubusercontent.com/172399/47855494-12f38a80-dde5-11e8-8e2e-f70bc8208da8.png)

It should generate
![image](https://user-images.githubusercontent.com/172399/47855569-43d3bf80-dde5-11e8-88b7-0339e11ce973.png)

**Comment by mjbvz** [comment]
Example case. Starting with:

```ts
// tslint:disable-next-line:array-type
let t: Array<string> = 1;;
```

Using the disable `whitespace` quick fix should generate:

```ts
// tslint:disable-next-line: array-type whitespace
let t: Array<string> = 1;;
```

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint. We are archiving this repo as this project is no longer maintained
