### ISSUE TITLE
Disable rule is often not shown

### ISSUE THREAD

**Issue by arogg** [Microsoft/typescript-tslint-plugin#22]
I believe disabling a rule on a line by line basis should **_always_** be an option. Currently it is not. Most of the time the option to disable **_a_** rule is not available ...even when the quick fix option to disable **_all_** is available.

I was about to migrate from the old project at https://github.com/angelozerr/tslint-language-service and I am wondering if this PR can be included into this project: https://github.com/angelozerr/tslint-language-service/pull/87 ?

I'm back to the old project for now where I have manually added this PR to my personal installation. But I just wanted to let you know because I just tried out this version and this is what was missing for me.

Or maybe I am missing something? Without the option to disable a rule, I must always look up the corresponding rule and type the comment to disable it by hand. Surely this is not intended? :)

Thank you.

Edit. example

```
const somevar = null as any;
const somevar2 = require(somevar);
```

This code shows 2 tslint errors (no-any and no-var-requires), but non of the disable rule quick fixes will show!

**Comment by mjbvz** [comment]
Make sense for tslint failures. Can you port that PR?

**Comment by arogg** [comment]
Not quite sure yet. Probably not but I'll let you know if I do.

**Comment by reduckted** [comment]
I've ported the PR into #36. 😄
