### ISSUE TITLE
tslint is telling me to use spaces in my js files

### ISSUE THREAD

**Issue by DanTup** [Microsoft/typescript-tslint-plugin#24]
I don't know if this is related to this plugin, but I just switched to it from the other one. After creating a JS file, I get a tslint error on every line telling me to indent with spaces:

<img width="581" alt="screen shot 2018-11-13 at 9 54 44 am" src="https://user-images.githubusercontent.com/1078012/48405587-71e0ca00-e72a-11e8-9bba-7a9b918343a6.png">

My `tslint.json` looks like this:

```js
{
	"extends": [
		"tslint:recommended"
	],
	"linterOptions": {
		"exclude": [
			"src/analysis/analysis_server_types.ts",
			"src/analysis/analyzer_gen.ts"
		]
	},
	"rulesDirectory": "lints/",
	"rules": {
		"disallow-fspath": true,
		"disallow-vscode-in-debuggers": true,
		"indent": {
			"options": "tabs"
		},
		"curly": false,
		"no-console": false,
		"max-classes-per-file": false,
		"interface-name": false,
		"member-ordering": false,
		"no-empty": {
			"options": "allow-empty-catch"
		},
		"space-before-function-paren": false,
	}
}
```

I'm not sure:

1. Why .js files are being linted by tslint
2. Why it's telling me it expects spaces when the config says tabs

**Comment by mjbvz** [comment]
Js validation should be off by default. I'm adding back a `jsEnable` plugin setting that will allow you to enable if again if desired

**Comment by DanTup** [comment]
That's fixed it, thanks!
