### ISSUE TITLE
TSLint should be less aggressive (part 2)

### ISSUE THREAD

**Issue by jrieken** [microsoft/typescript-tslint-plugin#26]
This extension bugs you until you install TSLint (globally or for each project) only to then annoy you with more errors about missing configuration.

**Comment by mjbvz** [comment]
This hasn't been the behavior in recent versions. But the lack of bugging is causing a lot of people to not understand why tslint is not loading or enabled.

The new behavior i'm adding is: report errors about loading tslint if there is a `tslint.json` in your workspace
