### ISSUE TITLE
Support auto-fix on save and/or quick fix for problems that can be --fix ed

### ISSUE THREAD

**Issue by Jessidhia** [Microsoft/typescript-tslint-plugin#29]
This is a feature of the old `tslint` vscode plugin but not of the service-based one. Previously autofixable rules have to either be autofixed externally or completely manually.

The "Quick fix" menu also shows "no code action available" even on lint warnings that there are autofixers; for example, the `ordered-imports` rule or the `semi` rule.

**Comment by floribon** [comment]
+1 for autofix support although not sure if my problem is the same.

I followed the install instructions but when I mouseover a tslint error I can't autofix it, unlike what is presented [on your screenshot](https://github.com/Microsoft/typescript-tslint-plugin/blob/master/documentation/example-vscode.png)

The other plugin would let me configure a keyboard shortcut to autofix any fixable errors on the current file which was very helpful.

**Comment by vincaslt** [comment]
You can find the 'auto-fix' by:
a) clicking on some underlined code, and clicking on the light bulb icon that appears nearby.
b) opening "Problems" view in vscode (ctrl+p -> View: Focus Problems)

You will not be able to bind this to a keyboard shortcut at the moment. To enable quickfix command from vscode is the responsibility of [vscode-typescript-tslint-plugin](https://github.com/Microsoft/vscode-typescript-tslint-plugin). It's currently in the works, so it doesn't have that functionality yet as well. You can see the progress in the [roadmap](https://github.com/Microsoft/typescript-tslint-plugin/issues/1.)

**Comment by xiaoxiangmoe** [comment]
@vincaslt It seems not work when I using workspace version of typescript in VSCode.

**Comment by xiaoxiangmoe** [comment]
Oh, we should restart VSCode after config.

**Comment by mjbvz** [comment]
TS plugins cannot reasonable implement auto fix on save today as plugins have no concept of 
"save". See my proposal against TS to support this: https://github.com/Microsoft/TypeScript/issues/29452

For the VS Code extension that ships this plugin, we are tracking support with  https://github.com/Microsoft/vscode-typescript-tslint-plugin/issues/2 and should be able to offer a preview of this functional shortly
