### ISSUE TITLE
TypeScript 2.4 - 2.8 support

### ISSUE THREAD

**Issue by killerDJO** [Microsoft/typescript-tslint-plugin#33]
Documentation states that this plugin requires TypeScript 2.4 or later. However, in the code there is a language services version hardcoded ([link](https://github.com/Microsoft/typescript-tslint-plugin/blob/2fa8c083c8d86926b74707ef23506eae9dd592b0/src/index.ts#L37)), which is valid only for TypeScript 2.9+. It seems like either documentation should be updated to reflect this or version restriction downgraded (I made a quick test with TS 2.6 which has 0.7 version of language services and everything seems to be working).

**Comment by mjbvz** [comment]
Documentation should be updated. We don't test the plugin with these version. Because a malfunctioning tsserver plugin can break the entire editor experinace, we've opted to restrict the plugin to versions of TypeScript that are known to work
