### ISSUE TITLE
Does not work with config as javascript file (instead of json)

### ISSUE THREAD

**Issue by emattias** [microsoft/typescript-tslint-plugin#34]
I need to define my `tslint.json` as javascript file. But when I specify the path to my `tslint.js` file the configuration is not picked up by this extension. 

My js config file works when I run tslint manually like so: `tslint --config ./tslint.js --project .`

**Comment by mjbvz** [comment]
We don't pick up js based config files by default but you can use the [`configFile` option](https://github.com/microsoft/typescript-tslint-plugin#configuration-options) to explicitly set which config file to use. 

I just added a test for this and it seems to work just fine
