### ISSUE TITLE
Difference between this and vscode-tslint?

### ISSUE THREAD

**Issue by ithinkihaveacat** [Microsoft/typescript-tslint-plugin#37]
What are the differences between typescript-tslint-plugin and vscode-tslint? When would one be preferred over the other?

(The README [explains that vscode-tslint should be disabled](https://github.com/Microsoft/typescript-tslint-plugin#with-vs-code) when this plugin is used, but not why.)

**Comment by mjbvz** [comment]
https://github.com/Microsoft/vscode-typescript-tslint-plugin#differences-with-the-vscode-tslint-extension
