### ISSUE TITLE
alwaysShowRuleFailuresAsWarnings doesn't change severity

### ISSUE THREAD

**Issue by Ky6uk** [microsoft/typescript-tslint-plugin#40]
I'm trying to migrate to this plugin from deprecated `vscode-tslint`. My configuration is

```json
{
  "extends": "./tsconfig.base",

  "plugins": [{
    "name": "typescript-tslint-plugin",
    "alwaysShowRuleFailuresAsWarnings": false
  }]
}
```

But `alwaysShowRuleFailuresAsWarnings` has no effect and errors are always displaying as warnings. `vscode-tslint` works fine.

VSCode v1.30.0
TypeScript v3.1.6 (workspace) and v3.2.2 (vscode)

**Comment by WhiteAbeLincoln** [comment]
I'm having the same issue

**Comment by mjbvz** [comment]
Did you configure the `tslint.json` to have  default level of warning?

**Comment by Ky6uk** [comment]
Nope. I also have severity "error" for rule I see as warning.

**Comment by craigsmitham** [comment]
We're experiencing the same issue. When we run lint via the CLI, we get errors/warnings as configured. In VS code they all appear as warnings. However, if I re-save the tsconfig file (even with no modifications), then after 15-20 seconds the plugin appears to honor the setting (the green squiggles change to red for errors).  It seems like the plugin is listening for tsconfig changes and applying the setting, but sadly doesn't appear to apply them correctly on initial load.

A side question, why is `alwaysShowRuleFailuresAsWarnings ` defaulted to true?

**Comment by Ky6uk** [comment]
I also found a strange behavior at `v0.3.1`. First time VSCode ignores `alwaysShowRuleFailuresAsWarnings: true` and displays errors as warnings. But when I tried to re-save `tsconfig.json` file with no changes the warnings magically turned to errors.

**Comment by jcyuan** [comment]
I'm encountering the same problem as what @craigsmitham describes

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint. We are archiving this repo as this project is no longer maintained
