### ISSUE TITLE
Add an "Editor Support" section for Vim with ALE

### ISSUE THREAD

**Issue by w0rp** [microsoft/typescript-tslint-plugin#44]
I've been supporting a variety of tsserver features directly and very well for a long time with [ALE](https://github.com/w0rp/ale). I'm opening this issue mostly to leave a note for myself to create a pull request to describe how to set up this plugin in ALE. All you have to essentially do is install ALE and set up `tsconfig.json`. The rest should just work.

For ALE, I strongly recommend using this plugin instead of running `tslint` on files directly.

**Comment by mjbvz** [comment]
Glad to hear it works. Yes please submit a PR that explains how to set up this plugin with ALE. I'm not familiar enough with Vim to do so myself

**Comment by rupurt** [comment]
@w0rp any updates on this?

**Comment by w0rp** [comment]
If there were updates, you would have seen them. Don't ask for updates from anyone on GitHub.

**Comment by jonaz** [comment]
If someone just writes a brief howto here as a comment i could help with adding proper docs to this repo.

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint. We are archiving this repo as this project is no longer maintained
