### ISSUE TITLE
Exclude doesn't work

### ISSUE THREAD

**Issue by jajaperson** [Microsoft/typescript-tslint-plugin#45]
I am getting the following warning in VSCode for some typescript-generated javascript:

```js
{
  "resource": ".../packages/cli/lib",
  "owner": "typescript",
  "code": "1",
  "severity": 4,
  "message": "variable name must be in lowerCamelCase, PascalCase or UPPER_CASE (variable-name)",
  "source": "tslint",
  "startLineNumber": 25,
  "startColumn": 7,
  "endLineNumber": 25,
  "endColumn": 15
}
```

I have "packages/*/lib" in my `tslint` configuration file's `exclude` option (its a `lerna` project), but the only way I can get the warning to disappear is by disabling javascript validation altogether.

**Comment by jajaperson** [comment]
Okay, I added a `tsconfig.json` at the route of my project, extending `tsconfig.base.json`, and the error still persists.

**Comment by mjbvz** [comment]
Closing as we need more information about the project's structure to investigate this
