### ISSUE TITLE
Typo: "suppress", not "supres" (two 'p's) 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/typescript-tslint-plugin#5]
Port of https://github.com/angelozerr/tslint-language-service/issues/57

`supressWhileTypeErrorsPresent` - should be `suppressWhileTypeErrorsPresent`. Incorrect spelling à la ["referer"](https://en.wikipedia.org/wiki/HTTP_referer#Etymology).

Can we change this now, while the plugin is new?

**Comment by mjbvz** [comment]
I made a breaking change to fix the spelling with the understanding that the plugin is still new and few users are likely to have explicitly configured this option
