### ISSUE TITLE
Can't get VS2017 to show errors in editor

### ISSUE THREAD

**Issue by hellocontrol-bng** [Microsoft/typescript-tslint-plugin#50]
Hi there -

I'm trying to set this up. I have followed the instructions listed in the readme, but I'm not seeing anything show up in VS2017's editor.

Here is my tsconfig.json:

```
{
	"compileOnSave": true,
	"compilerOptions": {
		"rootDir": "./",
		"preserveSymlinks": true,
		"baseUrl": "src",
		"allowSyntheticDefaultImports": true,

		"paths": {
			"*": [
				"./Client/node_modules/*",
				"./Client/node_modules/@types/*"
			],
			"@ApiIntermediary": [ "Global/Platform/ApiIntermediary" ],
			"@Utilities": [ "Utilities/index" ],
			"@Global/*": [ "Global/*" ],
			"@Components/*": [ "UI/Components/*" ],
			"@Areas/*": [ "UI/Areas/*" ],
			"@Boot/*": [ "UI/Boot/*" ],
			"@Styles/*": [ "Styles/*" ],
			"@UIKit/*": [ "UI/Components/UIKit/*" ]
		},

		"module": "esnext",
		"moduleResolution": "node",
		"target": "es6",
		"lib": [
			"es6",
			"es2015",
			"dom"
		],
		"jsx": "react",
		"sourceMap": true,
		"strict": false,
		"types": [
			"webpack-env"
		],
		"typeRoots": [
			"./Client/node_modules/@types"
		],
		"plugins": [
			{
				"name": "tslint-language-service",
				"configFile": "tslint.json",
				"suppressWhileTypeErrorsPresent": false,
			}
		]
	},
	"exclude": [
		"bin"
	]
}
```

My `tslint.json` file is a sibling to the `tsconfig.json` file. I have attached the [tslint.json](https://github.com/Microsoft/typescript-tslint-plugin/files/2809099/tslint.json.txt).

I have also installed `typescript-tslint-plugin` as well as `tslint`. I've verified that linting works at build time with webpack, but I'm having trouble getting VS2017 to show any kind of errors or warnings in the editor.

I'm happy to provide any other information!

VS2017 (15.9.6)
Project is set to use TS3.1 in the project properties

**Comment by mjbvz** [comment]
Sounds like https://github.com/Microsoft/typescript-lit-html-plugin/issues/11 but I think that specific issue does not apply to VS2017 15.9.6

Can you please try collecting the TSServer log as described in this comment: https://github.com/Microsoft/typescript-lit-html-plugin/issues/11#issuecomment-451230021

**Comment by hellocontrol-bng** [comment]
@mjbvz Solved! Looking at the logs, I realized I was dumb and had the old plugin name of `tslint-language-service` in there, from the plugin that preceded this one. I swapped it to `typescript-tslint-plugin` and it started to work.
