### ISSUE TITLE
.tsx file extension is not supported

### ISSUE THREAD

**Issue by xeoneux** [Microsoft/typescript-tslint-plugin#51]
The extension does not run for `.tsx` typescript react files...

**Comment by mjbvz** [comment]
Please share an example. It works for me:

![screen shot 2019-02-01 at 11 38 21 am](https://user-images.githubusercontent.com/12821956/52145482-eafb0980-2615-11e9-8be8-e54103a8ae41.png)

**Comment by barryblando** [comment]
> Please share an example. It works for me:
> 
> ![screen shot 2019-02-01 at 11 38 21 am](https://user-images.githubusercontent.com/12821956/52145482-eafb0980-2615-11e9-8be8-e54103a8ae41.png)

How did you make it work?

**Comment by mjbvz** [comment]
Install the extension and created a tsx file. It should just work

**Comment by mjbvz** [comment]
Closing as this needs more information to investigate
