### ISSUE TITLE
Does it work with TS 2.9?

### ISSUE THREAD

**Issue by mctep** [Microsoft/typescript-tslint-plugin#53]
Hi! Thank you for your job.

According to https://github.com/Microsoft/typescript-tslint-plugin/blob/c060a5384988c64fd84ff5cdc0cf07c8dcd73461/src/index.ts#L41

Looks like this plugin does not work with TypeScript 2.9. But README says that it requires TypeScript 2.9 or later.

**Comment by mjbvz** [comment]
THanks. It requires 3.0+
