### ISSUE TITLE
Will you provide typescript-eslint-plugin?

### ISSUE THREAD

**Issue by xiaoxiangmoe** [Microsoft/typescript-tslint-plugin#58]
This repo is TypeScript language service plugin for TSLint.

[TSLint in 2019](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) :
> In order to avoid bifurcating the linting tool space for TypeScript, we therefore plan to deprecate TSLint and focus our efforts instead on improving ESLint’s TypeScript support. 

Will you provide typescript-eslint-plugin after tslint deprecated?

**Comment by Swatinem** [comment]
Related question: https://github.com/typescript-eslint/typescript-eslint/issues/254

**Comment by mjbvz** [comment]
No active plans. There will still be projects relying on tslint for a while so this plugin is not going away
