### ISSUE TITLE
Displays wrong deprication warnings on overloaded methods

### ISSUE THREAD

**Issue by jsaalfeld** [Microsoft/typescript-tslint-plugin#59]
We're using rxjs in our projects and since a couple of months new deprecation have been added (https://github.com/ReactiveX/rxjs/commit/c85ddf695a038cdd16273ccb28d7dcb4e8e15662). Those deprecation overload the [standard-use case](https://github.com/ReactiveX/rxjs/blob/master/doc/observer.md) (The last one, that didn't change in the Observable.ts). But the plugin throws a deprecation warning for that use-case as well, even though it has no deprecation decorator.

![deprecated](https://user-images.githubusercontent.com/6213120/53472853-1e8c5080-3a69-11e9-964d-dd47acde890d.jpg)

**Comment by mjbvz** [comment]
Do you also see this when running tslint on the command line?

**Comment by jsaalfeld** [comment]
`ng lint` doesn't throw the error, it happens exclusively in the vscode-ui.

**Comment by mjbvz** [comment]
Wait, are you talking about the `@deprecated` markers in the quick info, or is tslint reporting actual errors in the file?

**Comment by jsaalfeld** [comment]
Like the screenshot shows and I stated in my last message, it is _just_ the quick info and the annotation in vscode that marks it as an error.

**Comment by mjbvz** [comment]
Ok, those hovers don't even come from this extension. Please file an issue against typescript instead

**Comment by mjbvz** [comment]
Opened https://github.com/Microsoft/TypeScript/issues/30181 to track this
