### ISSUE TITLE
Code cleanup: split index and runner into multiple files?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/typescript-tslint-plugin#6]
Porting https://github.com/angelozerr/tslint-language-service/issues/89: I'm finding it difficult to read through `index.ts` and `runner.ts`. Would you mind splitting out unrelated constructs like extra classes or only-once-used private functions into separate files, or accepting a PR from me doing so?

**Comment by mjbvz** [comment]
Actually, I'll handle the first part of this. Will submit changes shortly

**Comment by mjbvz** [comment]
Made initial pass but feel free to submit further prs
