### ISSUE TITLE
Allow usage of external tslint npm module

### ISSUE THREAD

**Issue by haugerbr** [microsoft/typescript-tslint-plugin#68]
Add a setting like "tslint.nodePath" to point to a tslint binary. This is especially helpful in scenarios where you want to make sure the lint errors you see in vscode match what you would get running it from the command line.

**Comment by poelstra** [comment]
This is somewhat related to https://github.com/Microsoft/vscode-typescript-tslint-plugin/issues/78, which is about automatically walking `tsconfig.json` `extends` fields to find the 'right' version of `tslint` to use.

**Comment by octogonz** [comment]
I agree with @poelstra .  When you have hundreds of projects in your monorepo, you want to minimize the amount of boilerplate that has to be copy+pasted into each project.  If we can discover the location of **tslint** based on **tslint.json** (e.g. by following the `extends` property), that's one less setting to manage.

**Comment by haugerbr** [comment]
I'm going to go ahead and close this since tslint is deprecated in favor of eslint and the eslint plugin supports this already.
