### ISSUE TITLE
Incorrect path resolution when running under coc.nvim

### ISSUE THREAD

**Issue by vsviridov** [microsoft/typescript-tslint-plugin#69]
I've traced the problem down to https://github.com/Microsoft/typescript-tslint-plugin/blob/master/src/runner/index.ts#L372. When running under `coc.nvim` `process.argv0` points to the `coc-nvim` binary, not `node`. This messes up path resolution for `tslint` and the whole thing seems to break.

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint. We are archiving this repo as this project is no longer maintained
