### ISSUE TITLE
disable-next-line statement not indented correctly

### ISSUE THREAD

**Issue by roblourens** [microsoft/typescript-tslint-plugin#73]
- Have an unused expression
- Invoke the quickfix to disable the rule
- The rule disable statement is not indented

![Apr-08-2019 16-46-16](https://user-images.githubusercontent.com/323878/55763884-dbd17700-5a1d-11e9-9110-c7d10353d4be.gif)

**Comment by mjbvz** [comment]
Simple repo for default tsconifg:

```ts
{
    const a = 1
}
```

Disable missing semicolon
