### ISSUE TITLE
Support of Visual Studio 2019

### ISSUE THREAD

**Issue by koljada** [Microsoft/typescript-tslint-plugin#74]
It seems like this plugin is not working in VS 2019 at all.
Example: https://prnt.sc/n9haqh (VS 2019 is on the right)

**Comment by amcasey** [comment]
Thanks!  @uniqueiniquity is going to take a look.

**Comment by uniqueiniquity** [comment]
Thanks for reporting, @koljada!
I'm not able to reproduce the issue; that is, the plugin works fine for me in VS 2019.
Could you produce a TypeScript language service log by following [these instructions](https://github.com/Microsoft/JSTSdocs/blob/master/articles/troubleshooting/index.md#enable-detailed-language-service-logging) and attach it here? That will help me diagnose the issue you're seeing.
Also, since it's not in the log, could you let me know the location of the `tslint.json` you're using? I couldn't tell from your screenshot.

Thanks again!

**Comment by koljada** [comment]
Hello @uniqueiniquity !
Here are my logs: [logs.zip](https://github.com/Microsoft/typescript-tslint-plugin/files/3084926/logs.zip)
`tslint.json` file is placed next to `tsconfig.json` in one of the nested folders inside `Scripts` directory: http://prntscr.com/ncp7jx
Thank you!

**Comment by uniqueiniquity** [comment]
Thanks for the logs!
It looks like the plugin is not able to be found by the language service; it's looking in `Scripts\dashboard\node_modules` (as well as `C:/Program Files (x86)/Microsoft SDKs/node_modules, but I assume you didn't try to install the plugin there). Where is the plugin installed?
Also, could you generate the same logs for your VS 2017 instance (assuming it's working for you there)? I don't think we changed how we look for plugins, but those logs will confirm for me.
Thanks!

**Comment by koljada** [comment]
It's not installed, I don't use npm for that project so I don't have `package.json` and `node_modules` folder.
But it somehow works in VS 2017. Here are my logs: 
[logsVS2017.zip](https://github.com/Microsoft/typescript-tslint-plugin/files/3089057/logsVS2017.zip)

Btw, do I need to set the environment variable value back or it has kind of one-run effect?

**Comment by uniqueiniquity** [comment]
Thanks for sending the logs.
From the second set of logs, it looks like you're not actually using this plugin to provide TSLint results in VS 2017. One way to see that is that in your original screenshot, the code for each warning in the error list is the name of the rule. However, as defined in [https://github.com/Microsoft/typescript-tslint-plugin/blob/master/src/config.ts], every error produced by `typescript-tslint-plugin` is given the code "1", and that's what I get when running it locally.

Is it possible you have some Visual Studio extension installed for your VS2017 instance that is providing the TSLint results?

**Comment by uniqueiniquity** [comment]
Also, yes, you will need to remove the environment variable if you want it to stop creating these logs.

**Comment by koljada** [comment]
@uniqueiniquity 
Thank you for your help! You're right, I guess [TypeScript Analyzer](https://marketplace.visualstudio.com/items?itemName=RichNewman.TypeScriptAnalyzer) produces those warnings(sorry, I forgot that I have this extension installed).

**Comment by uniqueiniquity** [comment]
@mjbvz I think this should be ok to close
