### ISSUE TITLE
Proposal: Support docker / docker-compose

### ISSUE THREAD

**Issue by gja** [Microsoft/typescript-tslint-plugin#75]
Hi All,

I was wondering if this plugin had any intention of being run via docker? I wanted to make a proposal here, and if this looks feasible I'll try working on it.

### Use Case

I currently have a TS project, which I develop via docker-compose. Since I'm on OSX, and docker runs on linux, I have node_modules as a volume mount. There are now two copies of every node_module downloaded, one for running the application, and one for VSCode's typescript checks.

### Proposed Architecture

Looks like tslint is loaded here: https://github.com/Microsoft/typescript-tslint-plugin/blob/master/src/runner/index.ts#L174

* The type of library is `typeof require('tslint')`, i'd propose making a compatible interface which just runs everything via `docker-compose run --rm service-name tslint`, passing options in via stdin and reading results out via stdout.
* This could work for long lived processes as well
* This would be configured via some flag `"useDockerCompose": "service-name"`
* As an aside, is `typeof require("tslint")` future proof? In case VSCode's TSLint updates type in a later version, and the project is behind, won't this barf?

**Comment by mjbvz** [comment]
Interesting proposal but out of scope for this plugin. It need to have it installed on the same machine as the version of TypeScript that is being used

If you want to run tslint in docker, I suggest you setup a VS Code task to run tslint instead
