### ISSUE TITLE
cyclomatic-complexity should increase on nested statements

### ISSUE THREAD

**Issue by jonnytest1** [microsoft/typescript-tslint-plugin#81]
the calculation of cyclomatic complexity should prioritize 

       `
       if(condition){   //+1
               //code
              return
       }
        if(condition){  //+1
              //code
              return
       }
       `
over 

       `
       if(condition){   //+1
               //code
              return
       }else{
             if(condition){  //+2
                   //code
                  return
             }
       }
      
       `

sonar analysis for example multiplies the complexity of nested flow statements like shown in the comments after the conditions

**Comment by mjbvz** [comment]
Does this also happen if you run tslint from the command line?

Can you please provide a complete code example that demonstrates this issue, including the `tslint.json` file
