### ISSUE TITLE
VSCode plugin: package manager option seems to be ignored

### ISSUE THREAD

**Issue by bluepichu** [microsoft/typescript-tslint-plugin#82]
I have a workspace in which I installed the required packages globally via `yarn`, and no matter what I set `tslint.packageManager` to in my settings, it would not work, and I would get error messages about installing with `npm`.  Globally installing with `npm` fixed my problem, but it seems like that shouldn't be necessary given that there seems to be logic for locating the global package directories for `yarn` and `pnpm` as well.

While trying to debug this, I happened to notice that several configuration options are not included [when `runTsLint` is invoked in `plugin.ts`](https://github.com/microsoft/typescript-tslint-plugin/blob/eb7eb2c24e655d8e73ee53f75ebec8c89c2800e5/src/plugin.ts#L145).  I'm not sure if this omission is intentional, but I think that passing through the `packageManager` option here would solve the problem.

**Comment by mjbvz** [comment]
Good find. Should be fixed in 0.5.4 by 071ebb724b1765a3d1295454f157bf96bfcb9cc8
