### ISSUE TITLE
Upgrade TSLint to 5.19.0 and release new version of plugin

### ISSUE THREAD

**Issue by jpike88** [microsoft/typescript-tslint-plugin#84]
@mjbvz tslint has been updated with some new rules, which are really useful

https://github.com/palantir/tslint/releases/tag/5.19.0

If you could update this plugin quickly that would be great

I've opened a PR to speed things up

Thanks

**Comment by mjbvz** [comment]
Note that the tslint version we use is only a dev dependency. We expect users of this extension to bring their own tslint versions (and 5.19.0 should work with the already published version of this plugin)
