### ISSUE TITLE
organizeImports always adds semicolon

### ISSUE THREAD

**Issue by bozdoz** [microsoft/typescript-tslint-plugin#86]
I'm using prettier without semicolons, with tslint.  When I save a file, it is auto-formatted with prettier, and auto-fixed with typescript.  However, the tslint plugin appears to be re-adding semi-colons after the imports are organized.   I have re-confirmed this in a devcontainer with the Remote Containers extension; just so I could isolate the issue.
 
Here are my files:

.prettierrc.yml:
```yml
semi: false
```

tslint.json:
```json
{
  "extends": [
    "tslint:recommended",
    "tslint-react",
    "tslint-config-airbnb",
    "tslint-config-prettier"
  ],
  "jsRules": {},
  "rulesDirectory": [],
  "rules": {
    "semicolon": [true, "never"]
  }
}
```

settings.json:
```json
"[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
},
"editor.codeActionsOnSave": {
    "source.fixAll": true,
    "source.organizeImports": true
}
```

App.tsx (Note the semi-colons at the end are re-added on every save):
```tsx
import Router from './Router';
import OrgSwitchDialog from './users/OrgSwitchDialog';
```

**Comment by bozdoz** [comment]
I should also say that my only/current solution is to install both this plugin and the deprecated plugin from `egamma`.  Using that deprecated plugin, I can auto-organize imports without semi-colons using this in settings.json:

Installing eg2.tslint and putting this in settings.json **works**:

```json
"tslint.autoFixOnSave": true
```

Anyway to get the non-deprecated plugin to work, would be fantastic.  Thanks!

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint. We are archiving this repo as this project is no longer maintained
