### ISSUE TITLE
[Q] tslint as peerDependency

### ISSUE THREAD

**Issue by manuth** [microsoft/typescript-tslint-plugin#89]
Hello
All the blog-posts and documentations of npm got me quite a bit confused.
If I understood it correctly peerDependencies are used when the author expects the user to have a certain dependency in his tree.

* Would it be a correct approach to add `tslint` to the `peerDependencies`-list in this project?
* Would it be a correct approach to also add `tslint` to the `peerDependencies`?
* Why did you decide against adding these modules to the `peerDependencies`?

Thank you so much for helping me out :smile:

**Comment by mjbvz** [comment]
This project dynamically loads tslint: https://github.com/microsoft/typescript-tslint-plugin/blob/3a7af0840999c122f8f51db44157d1ec2642867a/src/runner/index.ts#L144

We can load tslint from a number of different locations, including globally or from a path the user provides. That does not match how `peerDependency` are intended to be used
