### ISSUE TITLE
Tslint fixAll 

### ISSUE THREAD

**Issue by JulienB37** [microsoft/typescript-tslint-plugin#92]
Hi,

I have a problem with tslint on a single machine. I have tslint plugin installed in my VScode, errors are displayed  correcttly but i can't auto fix them. 
Right click does not show any tslint fix options. And fix all command in vscode does not work

i have tried uninstalling extensions and also uninstalling vscode but each time i have the same result.

This machine is on linux Mint

**Comment by JulienB37** [comment]
Same problème on other machine. But this time it is a Windows 10 machine

more info :
version vscode 1.51.1
version tslint : 1.2.3

**Comment by JulienB37** [comment]
On my personnal computer 
![image](https://user-images.githubusercontent.com/17041315/100735472-8c4d7500-33d1-11eb-9227-c7aa6c4e355c.png)
there is a light bulb near the warning 

On the vscode with the problème 
![image](https://user-images.githubusercontent.com/17041315/100735704-f403c000-33d1-11eb-8a6d-4e993f2d0995.png)
the warning stay as a standard warning

**Comment by mjbvz** [comment]
Closing as TSLint has been deprecated in favor of ESLint. We are archiving this repo as this project is no longer maintained
